name: nansari-test-snap-1
base: core20
version: '0.1.0'
title: nansari-test-snap
summary: A trivial snap application built via Github.
description: A simple snap. With an updated description. Goes to beta.

grade: stable
confinement: strict

apps:
  nansari-test-snap:
    command: src/hello.py

parts:
  main:
    source: .
    plugin: dump

  python:
    plugin: python

architectures:
  - build-on: [amd64]
